

name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      if: ${{ hashFiles('Podfile') != '' }}
      run: |
        sudo gem install cocoapods
        pod install

    - name: Build project
      run: xcodebuild -workspace OpenAIUser.xcworkspace -scheme OpenAIUser -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' build test

    - name: Test project
      if: ${{ hashFiles('OpenAIUserTests') != '' }}
      run: xcodebuild -workspace OpenAIUser.xcworkspace -scheme OpenAIUserTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' build test

    - name: Test UI
      if: ${{ hashFiles('OpenAIUserUITests') != '' }}
      run: xcodebuild -workspace OpenAIUser.xcworkspace -scheme OpenAIUserUITests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' build test